### ISSUE TITLE
Pasta raíz

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/mobile#1]
Há alguma motivação para ter a pasta redu-mobile como raíz? Já que o repositório precisa ser checked out numa pasta, pq não colocar o conteúdo de redu-mobile na raíz?

**Comment by thiagosoara** [comment]
Oi Guila... na verdade eu queria que ele ficasse na raiz mas na hora de gerar o código o eclipse incluiu o nome da posta do projeto... Hoje pela manhã tentei mudar isso e não consegui. Se tu puder mover todo o conteudo da pasta redu-mobile para a raiz não teria nenhum problema para mim. Qualquer coisa estarei quinta e sexta pela manhã.

**Comment by guiocavalcanti** [comment]
@thiagosoara acredito que basta entrar na pasta redu-mobile, dar um `git mv * ../` e commitar o resultado.

**Comment by guiocavalcanti** [comment]
@thiagosoara lembra de fechar os issues. É só adicionar `closes #numero` a mensagem do commit.
